/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import antlr.EdiLexer;
import antlr.EdiParser;
import antlr.dataClasses.EdiObject;
import antlr.visitors.MyEdiBaseVisitor;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        CharStream charStream = null;
        try {
            charStream = CharStreams.fromFileName("./test-file.txt");
        }catch (IOException e){
            System.out.println(e);
        }
        EdiLexer lexer = new EdiLexer(charStream);
        CommonTokenStream tokenStream = new CommonTokenStream(lexer);
        EdiParser parser = new EdiParser(tokenStream);

        EdiParser.EdiContext ediContext = parser.edi();
        MyEdiBaseVisitor visitor = new MyEdiBaseVisitor();
        EdiObject ediObject = (EdiObject) visitor.visit(ediContext);

        System.out.println("Done");
    }
}
